### ISSUE TITLE
Establish better upper limits for node and edge size, and edge arrow size and gaps

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/migraph#117]

**Comment by jhollway** [comment]
See for example the first lattice at the end of this page: https://snlab-ch.github.io/migraph/reference/create.html

**Comment by jaeltan** [comment]
I just ran pkgdown::build_site() on the latest version and the node size is much smaller

[Create networks with particular structures — create • migraph.pdf](https://github.com/snlab-ch/migraph/files/7660876/Create.networks.with.particular.structures.create.migraph.pdf)
