### ISSUE TITLE
Bug: Weights are removed when converting from different classes to other ones

### ISSUE THREAD

**Issue by BBieri** [snlab-ch/migraph#136]
I noticed while writing the tests for the S3 conversion methods that when one tries to switch from one network object class to the other with `as()` methods, results are inconsistent especially for weighted networks. 

More specifically, this occurs for example when one tries to do the following reprex:

``` r
 links <- data.frame(
     source = c("A", "A", "A", "A","J", "B", "B", "C", "C", "D"),
     target = c("B", "C", "D", "J","A","E", "F", "G", "H", "I"),
     weight = sample(1:20, 10, replace = T))
as_network(links)
# No edge attributes, where we should see a weight attribute
```

This can be fixed by automatically detecting whether the input object is weighted or not, fixing the `is_weighted()` test (where the `as_igraph()` conversion removes the weights before testing if there are weights due to the default input of the weight argument being `False` in the `as_igraph()` function) 

@jhollway Please let me know if I am unclear in the description of the bug

**Comment by jhollway** [comment]
Thanks @BBieri, just write up tests for what you expect functions to do, and then if they don't pass then I can either revise the functions or alter the tests.

**Comment by BBieri** [comment]
Note to self: check out [this](https://github.com/mbojan/intergraph/blob/master/R/asIgraph.R) script of conversion functions.
