### ISSUE TITLE
Add more guidance on how to put together visualisations

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/migraph#141]
See [this](https://ggplot2-book.org/networks.html) and [this](http://mr.schochastics.net/netVizR.html) link.

**Comment by jaeltan** [comment]
Added as vignette (p2visualisation.Rmd)

**Comment by jhollway** [comment]
I think this is looking pretty good @jaeltan , but I'm not sure whether we want to spend so much time on how to use igraph, sna etc, and instead just concentrate on what can be done with `autographr()` and, if more flexibility is required, `{ggraph}`.
Note also that we don't need anything about how to use the various object-plot methods in this vignette. Instead, what might be useful is to review current thinking about which layout algorithms work best for different kinds of networks, patterns, etc.

**Comment by jaeltan** [comment]
Ok noted. Regarding the review on layout algorithms, does this overlap with issue #152 ? Should I include the review in this vignette or in a separate one just for layouts?

**Comment by jhollway** [comment]
Yes, this is #152 . Let's pivot this vignette to be more about how to make effective visualisation choices with migraph/ggraph
