### ISSUE TITLE
Add package information on how to explore network data and obtain some descriptive statistics about nodes, ties, and attributes

### ISSUE THREAD

**Issue by ABiswasTortajada** [snlab-ch/migraph#154]
Issue raised during class on Nov 9, 2021

**Comment by BBieri** [comment]
Quick clarification question: is the goal to list network resources and/or to create a "getting started example workflow" of a network analysis project in the form of an additional vignette?

**Comment by jhollway** [comment]
Check with @ABiswasTortajada, but as I recall there was some interest in having some direction in how to identify, import, and manipulate network data.

**Comment by BBieri** [comment]
@ABiswasTortajada mentioned the following:
> Yes, the main concerns had to do with learning how to import, extract, and explore network data. Many students felt there were not enough elements walking a new user to figure out how to utilise the package, especially if they were not familiar with any other SNA package.
