### ISSUE TITLE
Retrieving info on how to use autographr yields a error in fetch

### ISSUE THREAD

**Issue by ABiswasTortajada** [snlab-ch/migraph#155]
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/migraph/help/migraph.rdb' is corrupt

**Comment by jhollway** [comment]
If using RStudio, try `.rs.restartR()` as suggested [here](https://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database)
