### ISSUE TITLE
as_network

### ISSUE THREAD

**Issue by hoffab** [snlab-ch/migraph#173]
**Describe the bug**
Using the as_network command on a specific igraph object (ffe_friends from the networkdata package) results in a multiplication of the number of vertices and edges, as well as loss of information on vertex attributes.

**Provide system information**
 - OS: MacOS Catalina 10.15.3
 - R version: 4.1.1
 - migraph version: 0.8.8

**To Reproduce**
1. Installed migraph and the package network data 
library(migraph)
library(networkdata)
data(package = "networkdata")
data("ffe_friends")
2. Tried to convert the igraph object into a network object
friends.network <- as_network(ffe_friends)
summary(friends.network)
3. See error: network object contains too many nodes and no more vertex attributes

**Expected behavior**
A conversion from an igraph to a network object that retains the original number of nodes as well as the vertex attributes.

**Additional context**

**Comment by BBieri** [comment]
Hi, 

Thanks a lot for using `{migraph}` and reporting the issue in such a detailed way, it made it easy for me to reproduce the error. I have just pushed a commit addressing your issue. Loops and attributes now get correctly converted and the number of vertices stays at 28.

You should be able to access this feature in the coming days when the next patch comes out. I'll reply on this thread when it will be the case.
