### ISSUE TITLE
Let edges be highlighted by function

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/migraph#224]
This should be similar to `autographr(data, node_measure = node_closeness)` but `autographr(data, edge_measure = edge_closeness)`. The same argument `identify_function` can be used to establish whether the max, min, etc is used.

**Comment by jhollway** [comment]
The current solution is perhaps a bit too clever. It accepts either a `node_` or `edge_` measure and cleverly plots it, but what if one wants to e.g. highlight the highest betweenness nodes _and_ edges? What do you think, @jaeltan and @ABiswasTortajada ? What would users find a good balance of straightforward and flexible?

**Comment by BBieri** [comment]
Hi @jhollway, thanks for the feedback! 
We could also implement the dual highlighting of edge and node with the statistic by providing a vector of length two to both highlighting arguments e.g. `highlight_function = c("ANodeMeasure", "AnEdgeMeasure")` and `identify_function = c("min", "max")`.

Happy to get feedback here from everyone @ABiswasTortajada @jaeltan :)
