### ISSUE TITLE
Add graphs to data examples

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/migraph#237]

**Comment by jhollway** [comment]
@jaeltan I've found a solution for this and implemented it for `mpn_elite_mex` and `mpn_elite_usa_advice` in the recent commits. Can you please use the same solution as for `mpn_elite_usa_advice` for all other networks? Then we can review how well our existing selection of datasets are plotted.

**Comment by jaeltan** [comment]
@jhollway done, some of the graphs probably need a different layout (eg. cow data, mpn_RepSxP)

**Comment by jhollway** [comment]
Great, can you maybe rank a checklist of the 5-10 most incomprehensible layouts, and we'll prioritise improving them for now.

**Comment by jaeltan** [comment]
Most incomprehensible layouts (in decreasing order):
[ ] mpn_cow_trade, mpn_cow_igo
[ ] mpn_senate112 (mpn_DemSxP, mpn_RepSxP, mpn_OverSxP)
[ ] mpn_bristol (too many edges in the center of the graph)
[ ] ison_marvel_teams/relationships
