### ISSUE TITLE
RE: Equivalence Tutorial (5)

### ISSUE THREAD

**Issue by znimess** [snlab-ch/migraph#258]
- [x] Suggestion 1: add a MCQ for [lines 164-164]
- [x] Suggestion 2: add an exercise for [lines 229-230] or MCQ
- [x] Suggestion 3: provide an explanation for "Reduced Graph"
- [x] Re: Suggestion 3 — how are "freaks", "squares", "nerds", and "geeks" broken down?
- [ ] Suggestion 4: make unit test questions into exercises (e.g., MCQ, or checked exercise "r_label-check") — we could provide object names to keep submissions uniform

**Comment by znimess** [comment]
Thanks for the update, @jhollway. Let me know if this referencing strategy is better.

- [ ] Re: Suggestion 1 — add a MCQ for this question: Why minimum? And what can we learn from this plot about where innovation might occur within this network? (Can be found right above "Structural Equivalence" section)
- [ ] Re: Suggestion 2 — add a MCQ for this question: Note also that the result is a weighted matrix; what would you do if you wanted it to be binary? (Can be found in "Step one: starting with a census" subsection)
- [ ] Re: Suggestion 4 — as the Unit Test questions stand, there are no solutions. We can either add hints/solutions or use "exercise.checker" option in the R code chunk.

**Comment by jhollway** [comment]
Can you try and implement a proposed solution for suggestion 4 then?

**Comment by jhollway** [comment]
Since neither `{gradethis}` nor `{checkr}` are available on CRAN at the moment, we'll need to skip such conversions of the unit tests and see whether the resources to do so are ready later in the year. Therefore, closing this issue for now.
