### ISSUE TITLE
RE: Centrality Tutorial (3)

### ISSUE THREAD

**Issue by znimess** [snlab-ch/migraph#259]
- [x] Suggestion: Added Q  [lines 111-120]. Can we add more options here instead of T/F? For example, the questions asked are "Are they equal? Why?" Maybe we can make this into a "select all that apply" type of question.
 
- [x] Do you want to make [line 210] into a MCQ?
- [ ] We might need to replace the Unit Test/Task questions (specifically 2 and 3) for grading purposes (looking ahead).

**Comment by jhollway** [comment]
Why don't you try and add some examples of research questions for different centrality measures, and then it can be a 'select all that might apply' kind of exercise?

**Comment by jhollway** [comment]
Since `{gradethis}` and `{checkr}` are not yet available on CRAN, will close this issue for now.
