### ISSUE TITLE
test_random() with network_equivalency() on bipartite network 

### ISSUE THREAD

**Issue by rabenton** [snlab-ch/migraph#272]
The test_random() function returns an error when testing network_equivalency() on a bipartite network.

`library(migraph)`
`network_equivalency(ison_southern_women)`
`test_random(ison_southern_women, network_equivalency, times=100)`

**Comment by jhollway** [comment]
Thank you @rabenton, this bug is now fixed in the develop branch. We will merge to the main branch and CRAN in the next week or two, or you can install via `remotes::install_github("snlab-ch/migraph", "develop")` if you need this functionality immediately.
